export { TitleSlider as ComponentTitleSlider } from "./TittleSlider"
export { ListMarker as ComponentListMaker } from "./Listmaker"
export { ButtonSlider as ComponentButtonSlider} from "./ButtonSlider"
export { Buttoninterface as ComponentButtonInterface} from "./Buttoninterface"
export { ButtonTakePicture as ComponentButtonTakePicture } from "./ButtonTakePicture"
export { Loading as ComponentLoading } from "./Loading"